use crate::ast::{Node, Spanned};

/// Walk the AST and emit a valid Arduino .ino sketch.
/// Arduino expects setup() and loop() instead of main().
/// wow maps shuru() -> setup() and chalao() -> loop().
pub fn generate(ast: &Spanned<Node>) -> String {
    let mut out = String::new();

    // Arduino sketches get a small subset of auzaar
    out.push_str("// Generated by wow\n");
    out.push_str("#include \"auzaar_arduino.h\"\n\n");

    if let Node::Program(stmts) = &ast.node {
        for stmt in stmts {
            out.push_str(&gen_node(stmt, 0));
        }
    }

    out
}

fn gen_node(node: &Spanned<Node>, depth: usize) -> String {
    let indent = "    ".repeat(depth);
    match &node.node {
        Node::ArduinoShuru(body) => {
            let mut s = String::from("void setup() {\n");
            for n in body {
                s.push_str(&gen_node(n, depth + 1));
            }
            s.push_str("}\n\n");
            s
        }
        Node::ArduinoChalao(body) => {
            let mut s = String::from("void loop() {\n");
            for n in body {
                s.push_str(&gen_node(n, depth + 1));
            }
            s.push_str("}\n\n");
            s
        }
        // TODO: implement remaining nodes in Phase 3
        _ => format!("{indent}/* TODO */\n"),
    }
}
