use crate::ast::{BinOp, InterpolPart, Node, Param, Spanned};
use std::collections::BTreeSet;

/// Walk the AST and emit a valid Arduino `.ino` sketch.
///
/// Arduino is memory-constrained and statically typed, so this backend is the
/// odd one out: instead of a dynamic value type it emits native C++ with
/// `double` as the single number type (cast to `int`/`unsigned long` at the
/// hardware-call boundary). The checker rejects the memory-heavy parts of wow
/// (lists, collection tools, `pucho`) before we ever get here.
///
/// wow maps `kaam shuru()` -> `setup()` and `kaam chalao()` -> `loop()`.
pub fn generate(ast: &Spanned<Node>) -> String {
    let stmts = match &ast.node {
        Node::Program(s) => s,
        _ => return String::new(),
    };

    // Sort the top level into globals, helper functions, setup and loop.
    let mut globals: Vec<(&String, &Spanned<Node>)> = Vec::new();
    let mut seen_globals: BTreeSet<String> = BTreeSet::new();
    let mut funcs: Vec<(&String, &Vec<Param>, &Vec<Spanned<Node>>)> = Vec::new();
    let mut shuru: Option<&Vec<Spanned<Node>>> = None;
    let mut chalao: Option<&Vec<Spanned<Node>>> = None;

    for stmt in stmts {
        match &stmt.node {
            Node::Assign { name, value } => globals.push((name, value)),
            Node::Kaam { naam, params, body } => funcs.push((naam, params, body)),
            Node::ArduinoShuru(body) => shuru = Some(body),
            Node::ArduinoChalao(body) => chalao = Some(body),
            _ => {} // the checker has already rejected anything else at top level
        }
    }

    // Top-level variables are true file-scope globals on Arduino, readable and
    // writable from setup()/loop()/helpers — so they must not be re-hoisted as
    // locals (that would reset them on every loop()).
    let global_names: BTreeSet<String> = globals.iter().map(|(n, _)| (*n).clone()).collect();

    let uses_bol = stmts.iter().any(uses_bol_in);

    let mut out = String::new();
    out.push_str("// Generated by wow — Code likho. Wow bolo.\n");
    out.push_str("#include \"auzaar_arduino.h\"\n\n");

    // Globals (each name declared once).
    if !globals.is_empty() {
        for (name, value) in &globals {
            if seen_globals.insert((*name).clone()) {
                out.push_str(&format!("double v_{name} = {};\n", gen_expr(value)));
            }
        }
        out.push('\n');
    }

    // Forward declarations carry the default-argument values.
    if !funcs.is_empty() {
        for (naam, params, _) in &funcs {
            out.push_str(&prototype(naam, params));
        }
        out.push('\n');

        for (naam, params, body) in &funcs {
            out.push_str(&gen_function(naam, params, body, &global_names));
        }
    }

    // setup()
    out.push_str("void setup() {\n");
    if uses_bol {
        out.push_str("    Serial.begin(9600);\n");
    }
    if let Some(body) = shuru {
        out.push_str(&declare_locals(body, &[], &global_names, 1));
        for stmt in body {
            out.push_str(&gen_stmt(stmt, 1));
        }
    }
    out.push_str("}\n\n");

    // loop()
    out.push_str("void loop() {\n");
    if let Some(body) = chalao {
        out.push_str(&declare_locals(body, &[], &global_names, 1));
        for stmt in body {
            out.push_str(&gen_stmt(stmt, 1));
        }
    }
    out.push_str("}\n");

    out
}

fn gen_function(
    naam: &str,
    params: &[Param],
    body: &[Spanned<Node>],
    globals: &BTreeSet<String>,
) -> String {
    let param_names: Vec<String> = params.iter().map(|p| p.name.clone()).collect();
    let ps: Vec<String> = params.iter().map(|p| format!("double v_{}", p.name)).collect();

    let mut s = format!("double f_{naam}({}) {{\n", ps.join(", "));
    s.push_str(&declare_locals(body, &param_names, globals, 1));
    for stmt in body {
        s.push_str(&gen_stmt(stmt, 1));
    }
    s.push_str("    return 0;\n}\n\n");
    s
}

fn prototype(naam: &str, params: &[Param]) -> String {
    // Defaults live on the prototype (C++ allows them in exactly one place).
    let ps: Vec<String> = params
        .iter()
        .map(|p| match &p.default {
            Some(def) => format!("double v_{} = {}", p.name, gen_expr(def)),
            None => format!("double v_{}", p.name),
        })
        .collect();
    format!("double f_{naam}({});\n", ps.join(", "))
}

// ----------------------------------------------------------------
// Statements
// ----------------------------------------------------------------

fn gen_stmt(node: &Spanned<Node>, depth: usize) -> String {
    let pad = "    ".repeat(depth);
    match &node.node {
        Node::Assign { name, value } => format!("{pad}v_{name} = {};\n", gen_expr(value)),
        Node::Bol(e) => format!("{pad}wow_print({});\n", gen_expr(e)),
        Node::Do(e) => format!("{pad}return {};\n", gen_expr(e)),
        Node::Roko => format!("{pad}break;\n"),
        Node::Aage => format!("{pad}continue;\n"),

        Node::Agar { condition, then_body, else_ifs, else_body } => {
            let mut s = format!("{pad}if ({}) {{\n", gen_expr(condition));
            s.push_str(&gen_block(then_body, depth + 1));
            for (cond, body) in else_ifs {
                s.push_str(&format!("{pad}}} else if ({}) {{\n", gen_expr(cond)));
                s.push_str(&gen_block(body, depth + 1));
            }
            if let Some(body) = else_body {
                s.push_str(&format!("{pad}}} else {{\n"));
                s.push_str(&gen_block(body, depth + 1));
            }
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        Node::HarRange { var, from, to, body } => {
            // inclusive: 0 se 10 tak -> 0..10
            let mut s = format!(
                "{pad}for (double v_{var} = {}; v_{var} <= {}; v_{var} += 1) {{\n",
                gen_expr(from),
                gen_expr(to)
            );
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        Node::Baar { times, body } => {
            let mut s = format!("{pad}for (double _k = 0; _k < ({}); _k += 1) {{\n", gen_expr(times));
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        Node::Jabtak { condition, body } => {
            let mut s = format!("{pad}while ({}) {{\n", gen_expr(condition));
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        _ => format!("{pad}{};\n", gen_expr(node)),
    }
}

fn gen_block(body: &[Spanned<Node>], depth: usize) -> String {
    let mut s = String::new();
    for stmt in body {
        s.push_str(&gen_stmt(stmt, depth));
    }
    s
}

// ----------------------------------------------------------------
// Expressions
// ----------------------------------------------------------------

fn gen_expr(node: &Spanned<Node>) -> String {
    match &node.node {
        // {:?} guarantees a decimal point so 5/2 is double division (2.5), not 2
        Node::Number(n) => format!("{n:?}"),
        Node::Str(s) => format!("\"{}\"", escape_cpp(s)),
        Node::Bool(b) => if *b { "true".into() } else { "false".into() },
        Node::Null => "0".into(),
        Node::Identifier(id) => map_ident(id),

        Node::Interpolated(parts) => {
            let pieces: Vec<String> = parts
                .iter()
                .map(|part| match part {
                    InterpolPart::Text(t) => format!("wow_str(\"{}\")", escape_cpp(t)),
                    InterpolPart::Expr(e) => format!("wow_str({})", gen_expr(e)),
                })
                .collect();
            format!("({})", pieces.join(" + "))
        }

        Node::Negate(e) => format!("(-({}))", gen_expr(e)),
        Node::UnaryNot(e) => format!("(!({}))", gen_expr(e)),

        Node::BinOp { op, left, right } => {
            let l = gen_expr(left);
            let r = gen_expr(right);
            match op {
                BinOp::Mod => format!("fmod({l}, {r})"), // % is integer-only in C++
                BinOp::And => format!("({l} && {r})"),
                BinOp::Or => format!("({l} || {r})"),
                _ => format!("({l} {} {r})", binop_sym(op)),
            }
        }

        Node::Ternary { condition, then_val, else_val } => format!(
            "(({}) ? ({}) : ({}))",
            gen_expr(condition),
            gen_expr(then_val),
            gen_expr(else_val)
        ),

        Node::Call { name, args } => gen_call(name, args),

        Node::Phir { value, calls } => {
            let mut acc: Spanned<Node> = (**value).clone();
            for step in calls {
                let mut new_args = Vec::with_capacity(step.args.len() + 1);
                new_args.push(acc);
                new_args.extend(step.args.iter().cloned());
                acc = Spanned::new(
                    Node::Call { name: step.name.clone(), args: new_args },
                    step.span.clone(),
                );
            }
            gen_expr(&acc)
        }

        _ => "0 /* unsupported on Arduino */".into(),
    }
}

fn gen_call(name: &str, args: &[Spanned<Node>]) -> String {
    let a: Vec<String> = args.iter().map(gen_expr).collect();
    match name {
        // Hardware — cast to the integer types the Arduino API expects.
        "pin_set" => format!("pinMode((int)({}), {})", arg(&a, 0), arg(&a, 1)),
        "pin_likho" => format!("digitalWrite((int)({}), {})", arg(&a, 0), arg(&a, 1)),
        "pin_parho" => format!("digitalRead((int)({}))", arg(&a, 0)),
        "intezar" => format!("delay((unsigned long)({}))", arg(&a, 0)),
        _ if is_arduino_math(name) => format!("wow_{name}({})", a.join(", ")),
        _ => format!("f_{name}({})", a.join(", ")),
    }
}

fn arg(a: &[String], i: usize) -> String {
    a.get(i).cloned().unwrap_or_else(|| "0".to_string())
}

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

/// Bare identifiers that name Arduino constants.
fn map_ident(name: &str) -> String {
    match name {
        "output" => "OUTPUT".into(),
        "input" => "INPUT".into(),
        "input_pullup" => "INPUT_PULLUP".into(),
        "on" => "HIGH".into(),
        "off" => "LOW".into(),
        _ => format!("v_{name}"),
    }
}

fn is_arduino_math(name: &str) -> bool {
    matches!(
        name,
        "round" | "round_up" | "round_down" | "square_root" | "power"
            | "absolute" | "random" | "random_number"
    )
}

fn binop_sym(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "==",
        BinOp::NotEq => "!=",
        BinOp::Lt => "<",
        BinOp::Lte => "<=",
        BinOp::Gt => ">",
        BinOp::Gte => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

fn escape_cpp(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out
}

// ----------------------------------------------------------------
// Local hoisting (wow variables are function-scoped, C++ blocks are not)
// ----------------------------------------------------------------

fn declare_locals(
    body: &[Spanned<Node>],
    params: &[String],
    globals: &BTreeSet<String>,
    depth: usize,
) -> String {
    let mut names = BTreeSet::new();
    for stmt in body {
        collect_assigns(stmt, &mut names);
    }
    let pad = "    ".repeat(depth);
    let mut out = String::new();
    for name in &names {
        if params.iter().any(|p| p == name) || globals.contains(name) {
            continue;
        }
        out.push_str(&format!("{pad}double v_{name} = 0;\n"));
    }
    out
}

fn collect_assigns(node: &Spanned<Node>, names: &mut BTreeSet<String>) {
    match &node.node {
        Node::Assign { name, .. } => {
            names.insert(name.clone());
        }
        Node::Agar { then_body, else_ifs, else_body, .. } => {
            for s in then_body {
                collect_assigns(s, names);
            }
            for (_, body) in else_ifs {
                for s in body {
                    collect_assigns(s, names);
                }
            }
            if let Some(body) = else_body {
                for s in body {
                    collect_assigns(s, names);
                }
            }
        }
        Node::HarRange { body, .. } | Node::Baar { body, .. } | Node::Jabtak { body, .. } => {
            for s in body {
                collect_assigns(s, names);
            }
        }
        _ => {}
    }
}

fn uses_bol_in(node: &Spanned<Node>) -> bool {
    match &node.node {
        Node::Bol(_) => true,
        Node::ArduinoShuru(body) | Node::ArduinoChalao(body) | Node::Kaam { body, .. } => {
            body.iter().any(uses_bol_in)
        }
        Node::Agar { then_body, else_ifs, else_body, .. } => {
            then_body.iter().any(uses_bol_in)
                || else_ifs.iter().any(|(_, b)| b.iter().any(uses_bol_in))
                || else_body.as_ref().map_or(false, |b| b.iter().any(uses_bol_in))
        }
        Node::HarRange { body, .. } | Node::Baar { body, .. } | Node::Jabtak { body, .. } => {
            body.iter().any(uses_bol_in)
        }
        _ => false,
    }
}
