use crate::ast::{BinOp, InterpolPart, Node, Param, Spanned};
use std::collections::BTreeSet;
use std::collections::HashMap;

/// Walk the AST and emit valid C source code.
///
/// The output is a single .c file compiled by gcc against the tools runtime
/// (runtime/tools/tools.h), which the CLI writes next to it. wow is a
/// dynamically typed language, so every value becomes a `WowValue` and every
/// operation a runtime call.
pub fn generate(ast: &Spanned<Node>) -> String {
    let mut g = CGen::new();

    let stmts = match &ast.node {
        Node::Program(s) => s,
        _ => return String::new(),
    };

    g.uses_koshish = stmts.iter().any(uses_koshish);

    // Pass 1: record every user function's signature so call sites can pad
    // missing arguments with their default values.
    for stmt in stmts {
        if let Node::Banao { naam, params, .. } = &stmt.node {
            g.funcs.insert(naam.clone(), params.clone());
        }
    }

    // Pass 2: generate the function bodies and the main body. This also fills
    // g.lifted with the lambda-lifted predicate functions used by chuno/badlo/etc.
    let mut func_defs = String::new();
    let mut main_body = String::new();

    for stmt in stmts {
        match &stmt.node {
            Node::Banao { naam, params, body } => {
                func_defs.push_str(&g.gen_function(naam, params, body));
            }
            // Top-level statements run inside main().
            _ => main_body.push_str(&g.gen_stmt(stmt, 1)),
        }
    }

    // Assemble the file in dependency order:
    //   includes -> prototypes -> lifted lambdas -> functions -> main
    let mut out = String::new();
    out.push_str("/* Generated by wow — Code likho. Wow bolo. */\n");
    out.push_str("#include \"tools.h\"\n\n");

    if !g.funcs.is_empty() {
        for (name, params) in &g.funcs {
            out.push_str(&prototype(name, params));
        }
        out.push('\n');
    }

    for lam in &g.lifted {
        out.push_str(lam);
    }
    if !g.lifted.is_empty() {
        out.push('\n');
    }

    out.push_str(&func_defs);

    out.push_str("int main(void) {\n");
    out.push_str("    srand((unsigned)time(NULL));\n");
    out.push_str(&declare_locals(stmts, &[], 1));
    if g.uses_koshish {
        out.push_str("    int _hbase = wow_handler_top;\n");
    }
    out.push_str(&main_body);
    out.push_str("    return 0;\n}\n");

    out
}

struct CGen {
    /// user function name -> its parameters (for default-argument padding)
    funcs: HashMap<String, Vec<Param>>,
    /// lambda-lifted predicate functions, emitted at the top of the file
    lifted: Vec<String>,
    /// counter for generating unique temp / lambda names
    tmp: usize,
    /// does the program use koshish? (gates the error-handler bookkeeping so
    /// ordinary programs stay clean)
    uses_koshish: bool,
    /// handler-stack variable for each enclosing loop, so roko/aage can unwind
    /// any koshish opened inside the loop body
    loop_stack: Vec<String>,
}

impl CGen {
    fn new() -> Self {
        CGen { funcs: HashMap::new(), lifted: Vec::new(), tmp: 0, uses_koshish: false, loop_stack: Vec::new() }
    }

    fn fresh(&mut self) -> usize {
        let n = self.tmp;
        self.tmp += 1;
        n
    }

    // ----------------------------------------------------------------
    // Functions
    // ----------------------------------------------------------------

    fn gen_function(&mut self, naam: &str, params: &[Param], body: &[Spanned<Node>]) -> String {
        let param_names: Vec<String> = params.iter().map(|p| p.name.clone()).collect();

        let mut sig = format!("WowValue f_{naam}(");
        if params.is_empty() {
            sig.push_str("void");
        } else {
            let ps: Vec<String> = params.iter().map(|p| format!("WowValue v_{}", p.name)).collect();
            sig.push_str(&ps.join(", "));
        }
        sig.push_str(") {\n");

        sig.push_str(&declare_locals(body, &param_names, 1));
        if self.uses_koshish {
            sig.push_str("    int _hbase = wow_handler_top;\n");
        }
        for stmt in body {
            sig.push_str(&self.gen_stmt(stmt, 1));
        }
        // A function with no explicit `bhejo` still returns a value.
        sig.push_str("    return wow_null();\n}\n\n");
        sig
    }

    // ----------------------------------------------------------------
    // Statements
    // ----------------------------------------------------------------

    fn gen_stmt(&mut self, node: &Spanned<Node>, depth: usize) -> String {
        let pad = "    ".repeat(depth);
        match &node.node {
            Node::Assign { name, value } => {
                format!("{pad}v_{name} = {};\n", self.gen_expr(value))
            }
            Node::PropAssign { object, prop, value } => {
                format!(
                    "{pad}wow_obj_set({}, \"{}\", {});\n",
                    self.gen_expr(object),
                    escape_c(prop),
                    self.gen_expr(value)
                )
            }
            Node::Likho(e) => format!("{pad}wow_print({});\n", self.gen_expr(e)),
            // Returning/breaking out of a koshish body must unwind the handler
            // stack first; _hbase is the function's level, the loop var the loop's.
            Node::Bhejo(e) => {
                let val = self.gen_expr(e);
                if self.uses_koshish {
                    // evaluate first (it may raise into an active koshish), then
                    // unwind the handler stack to this function's base and return
                    format!("{pad}{{ WowValue _ret = {val}; wow_handler_top = _hbase; return _ret; }}\n")
                } else {
                    format!("{pad}return {val};\n")
                }
            }
            Node::Roko => self.loop_exit(&pad, "break"),
            Node::Aage => self.loop_exit(&pad, "continue"),

            Node::Agar { condition, then_body, else_ifs, else_body } => {
                let mut s = format!("{pad}if (wow_truthy({})) {{\n", self.gen_expr(condition));
                s.push_str(&self.gen_body(then_body, depth + 1));
                for (cond, body) in else_ifs {
                    s.push_str(&format!("{pad}}} else if (wow_truthy({})) {{\n", self.gen_expr(cond)));
                    s.push_str(&self.gen_body(body, depth + 1));
                }
                if let Some(body) = else_body {
                    s.push_str(&format!("{pad}}} else {{\n"));
                    s.push_str(&self.gen_body(body, depth + 1));
                }
                s.push_str(&format!("{pad}}}\n"));
                s
            }

            Node::HarRange { var, from, to, body } => {
                let i = self.fresh();
                let from_c = self.gen_expr(from);
                let to_c = self.gen_expr(to);
                let mut s = format!("{pad}{{\n");
                s.push_str(&self.loop_enter(&pad, i));
                // `0 se 10 tak` counts inclusively: 0,1,...,10
                s.push_str(&format!("{pad}    double _to{i} = wow_as_num({to_c});\n"));
                s.push_str(&format!(
                    "{pad}    for (double _k{i} = wow_as_num({from_c}); _k{i} <= _to{i}; _k{i} += 1) {{\n"
                ));
                s.push_str(&format!("{pad}        WowValue v_{var} = wow_num(_k{i});\n"));
                s.push_str(&self.gen_body(body, depth + 2));
                s.push_str(&format!("{pad}    }}\n{pad}}}\n"));
                self.loop_leave();
                s
            }

            Node::HarList { var, list, body } => {
                let i = self.fresh();
                let list_c = self.gen_expr(list);
                let mut s = format!("{pad}{{\n");
                s.push_str(&self.loop_enter(&pad, i));
                s.push_str(&format!("{pad}    WowValue _lst{i} = {list_c};\n"));
                s.push_str(&format!(
                    "{pad}    for (int _i{i} = 0; _i{i} < wow_count(_lst{i}); _i{i}++) {{\n"
                ));
                s.push_str(&format!("{pad}        WowValue v_{var} = wow_at(_lst{i}, _i{i});\n"));
                s.push_str(&self.gen_body(body, depth + 2));
                s.push_str(&format!("{pad}    }}\n{pad}}}\n"));
                self.loop_leave();
                s
            }

            Node::Baar { times, body } => {
                let i = self.fresh();
                let times_c = self.gen_expr(times);
                let mut s = format!("{pad}{{\n");
                s.push_str(&self.loop_enter(&pad, i));
                s.push_str(&format!("{pad}    double _n{i} = wow_as_num({times_c});\n"));
                s.push_str(&format!("{pad}    for (double _k{i} = 0; _k{i} < _n{i}; _k{i} += 1) {{\n"));
                s.push_str(&self.gen_body(body, depth + 2));
                s.push_str(&format!("{pad}    }}\n{pad}}}\n"));
                self.loop_leave();
                s
            }

            Node::Jabtak { condition, body } => {
                let i = self.fresh();
                let cond_c = self.gen_expr(condition);
                let mut s = format!("{pad}{{\n");
                s.push_str(&self.loop_enter(&pad, i));
                s.push_str(&format!("{pad}    while (wow_truthy({cond_c})) {{\n"));
                s.push_str(&self.gen_body(body, depth + 2));
                s.push_str(&format!("{pad}    }}\n{pad}}}\n"));
                self.loop_leave();
                s
            }

            Node::Koshish { body, catch_var, catch_body } => {
                let i = self.fresh();
                let mut s = format!("{pad}{{\n");
                s.push_str(&format!("{pad}    int _h{i} = wow_handler_top;\n"));
                s.push_str(&format!("{pad}    wow_handler_top = _h{i} + 1;\n"));
                s.push_str(&format!("{pad}    if (setjmp(wow_handlers[_h{i}]) == 0) {{\n"));
                s.push_str(&self.gen_body(body, depth + 2));
                s.push_str(&format!("{pad}        wow_handler_top = _h{i};\n"));
                s.push_str(&format!("{pad}    }} else {{\n"));
                s.push_str(&format!("{pad}        wow_handler_top = _h{i};\n"));
                if let Some(var) = catch_var {
                    s.push_str(&format!("{pad}        WowValue v_{var} = wow_str(wow_error_msg);\n"));
                }
                s.push_str(&self.gen_body(catch_body, depth + 2));
                s.push_str(&format!("{pad}    }}\n{pad}}}\n"));
                s
            }

            // Everything else is an expression used for its effect (a call, etc.)
            _ => format!("{pad}{};\n", self.gen_expr(node)),
        }
    }

    fn gen_body(&mut self, body: &[Spanned<Node>], depth: usize) -> String {
        let mut s = String::new();
        for stmt in body {
            s.push_str(&self.gen_stmt(stmt, depth));
        }
        s
    }

    /// Record the handler level at a loop's start so roko/aage can unwind any
    /// koshish opened inside it. No-op unless the program uses koshish.
    fn loop_enter(&mut self, pad: &str, i: usize) -> String {
        if !self.uses_koshish {
            return String::new();
        }
        self.loop_stack.push(format!("_hl{i}"));
        format!("{pad}    int _hl{i} = wow_handler_top;\n")
    }

    fn loop_leave(&mut self) {
        if self.uses_koshish {
            self.loop_stack.pop();
        }
    }

    /// `break` / `continue`, restoring the handler stack to the loop's level.
    fn loop_exit(&self, pad: &str, kw: &str) -> String {
        if self.uses_koshish {
            if let Some(h) = self.loop_stack.last() {
                return format!("{pad}wow_handler_top = {h}; {kw};\n");
            }
        }
        format!("{pad}{kw};\n")
    }

    // ----------------------------------------------------------------
    // Expressions
    // ----------------------------------------------------------------

    fn gen_expr(&mut self, node: &Spanned<Node>) -> String {
        match &node.node {
            Node::Number(n) => format!("wow_num({n})"),
            Node::Str(s) => format!("wow_str(\"{}\")", escape_c(s)),
            Node::Bool(b) => format!("wow_bool({})", if *b { 1 } else { 0 }),
            Node::Null => "wow_null()".to_string(),
            Node::Identifier(id) => format!("v_{id}"),

            Node::Interpolated(parts) => {
                // Fold the parts into a string with wow_add (which concatenates
                // whenever a string is involved). Seed with "" so a leading
                // {number} still produces a string.
                let mut acc = String::from("wow_str(\"\")");
                for part in parts {
                    let piece = match part {
                        InterpolPart::Text(t) => format!("wow_str(\"{}\")", escape_c(t)),
                        InterpolPart::Expr(e) => self.gen_expr(e),
                    };
                    acc = format!("wow_add({acc}, {piece})");
                }
                acc
            }

            Node::List(items) => {
                if items.is_empty() {
                    "wow_list_lit(0, 0)".to_string()
                } else {
                    let vals: Vec<String> = items.iter().map(|it| self.gen_expr(it)).collect();
                    format!("wow_list_lit({}, (WowValue[]){{{}}})", items.len(), vals.join(", "))
                }
            }

            Node::Object { pairs } => {
                if pairs.is_empty() {
                    "wow_obj_new()".to_string()
                } else {
                    let keys: Vec<String> = pairs.iter()
                        .map(|(k, _)| format!("\"{}\"", escape_c(k)))
                        .collect();
                    let vals: Vec<String> = pairs.iter()
                        .map(|(_, v)| self.gen_expr(v))
                        .collect();
                    format!(
                        "wow_obj_lit({}, (const char*[]){{{}}}, (WowValue[]){{{}}})",
                        pairs.len(),
                        keys.join(", "),
                        vals.join(", ")
                    )
                }
            }

            Node::PropAccess { object, prop } => {
                format!("wow_obj_get({}, \"{}\")", self.gen_expr(object), escape_c(prop))
            }

            Node::SafePropAccess { object, prop } => {
                format!("wow_safe_get({}, \"{}\")", self.gen_expr(object), escape_c(prop))
            }

            Node::Negate(e) => format!("wow_neg({})", self.gen_expr(e)),
            Node::UnaryNot(e) => format!("wow_not({})", self.gen_expr(e)),

            Node::BinOp { op, left, right } => {
                let l = self.gen_expr(left);
                let r = self.gen_expr(right);
                format!("{}({l}, {r})", binop_fn(op))
            }

            Node::Ternary { condition, then_val, else_val } => {
                // C's ?: needs a plain int test, hence wow_truthy.
                let c = self.gen_expr(condition);
                let t = self.gen_expr(then_val);
                let e = self.gen_expr(else_val);
                format!("(wow_truthy({c}) ? ({t}) : ({e}))")
            }

            Node::Pucho(prompt) => format!("wow_pucho({})", self.gen_expr(prompt)),

            Node::Call { name, args } => self.gen_call(name, args),

            // phir desugars to nested calls: `a phir f(b)` == `f(a, b)`.
            Node::Phir { value, calls } => {
                let mut acc: Spanned<Node> = (**value).clone();
                for step in calls {
                    let mut new_args = Vec::with_capacity(step.args.len() + 1);
                    new_args.push(acc);
                    new_args.extend(step.args.iter().cloned());
                    acc = Spanned::new(
                        Node::Call { name: step.name.clone(), args: new_args },
                        step.span.clone(),
                    );
                }
                self.gen_expr(&acc)
            }

            _ => "wow_null() /* unsupported expression on C target */".to_string(),
        }
    }

    fn gen_call(&mut self, name: &str, args: &[Spanned<Node>]) -> String {
        // joro (reduce): the kid's expression uses two implicit names, `acc`
        // and `x`, so it is lifted into a two-argument function.
        if name == "joro" && args.len() == 3 {
            let list = self.gen_expr(&args[0]);
            let lam = self.lift_lambda2(&args[1]);
            let start = self.gen_expr(&args[2]);
            return format!("wow_joro({list}, {lam}, {start})");
        }

        // Higher-order tools: lift the kid's `x`-expression predicate
        // (the second argument) into a top-level C function.
        if is_higher_order(name) && args.len() == 2 {
            let list = self.gen_expr(&args[0]);
            let lam = self.lift_lambda(&args[1]);
            return format!("wow_{name}({list}, {lam})");
        }

        if is_builtin(name) {
            let a: Vec<String> = args.iter().map(|x| self.gen_expr(x)).collect();
            return format!("wow_{name}({})", a.join(", "));
        }

        // User function — pad any missing trailing arguments with their defaults.
        let params = self.funcs.get(name).cloned();
        let mut arg_strs: Vec<String> = args.iter().map(|x| self.gen_expr(x)).collect();
        if let Some(params) = params {
            for p in params.iter().skip(arg_strs.len()) {
                match &p.default {
                    Some(def) => arg_strs.push(self.gen_expr(def)),
                    None => arg_strs.push("wow_null()".to_string()),
                }
            }
        }
        format!("f_{name}({})", arg_strs.join(", "))
    }

    /// Lift `x > 5` into `static WowValue _lam_N(WowValue v_x) { return ...; }`
    /// and return the function's name to use as a pointer.
    fn lift_lambda(&mut self, pred: &Spanned<Node>) -> String {
        let body = self.gen_expr(pred);
        let n = self.fresh();
        let name = format!("_lam_{n}");
        self.lifted.push(format!(
            "static WowValue {name}(WowValue v_x) {{\n    return {body};\n}}\n"
        ));
        name
    }

    /// Lift a two-argument reducer `acc + x` for joro.
    fn lift_lambda2(&mut self, body_expr: &Spanned<Node>) -> String {
        let body = self.gen_expr(body_expr);
        let n = self.fresh();
        let name = format!("_lam_{n}");
        self.lifted.push(format!(
            "static WowValue {name}(WowValue v_acc, WowValue v_x) {{\n    return {body};\n}}\n"
        ));
        name
    }
}

// ----------------------------------------------------------------
// Variable hoisting
// ----------------------------------------------------------------

/// Emit `WowValue v_x = wow_null();` for every variable assigned anywhere in a
/// body. wow variables are function-scoped (like JS `var`), but C blocks are
/// not, so we hoist every assignment to the top of the enclosing function.
fn declare_locals(body: &[Spanned<Node>], params: &[String], depth: usize) -> String {
    let mut names = BTreeSet::new();
    for stmt in body {
        collect_assigns(stmt, &mut names);
    }
    let pad = "    ".repeat(depth);
    let mut out = String::new();
    for name in &names {
        if params.iter().any(|p| p == name) {
            continue;
        }
        out.push_str(&format!("{pad}WowValue v_{name} = wow_null();\n"));
    }
    out
}

fn collect_assigns(node: &Spanned<Node>, names: &mut BTreeSet<String>) {
    match &node.node {
        Node::Assign { name, .. } => {
            names.insert(name.clone());
        }
        Node::Agar { then_body, else_ifs, else_body, .. } => {
            for s in then_body {
                collect_assigns(s, names);
            }
            for (_, body) in else_ifs {
                for s in body {
                    collect_assigns(s, names);
                }
            }
            if let Some(body) = else_body {
                for s in body {
                    collect_assigns(s, names);
                }
            }
        }
        Node::HarRange { body, .. }
        | Node::HarList { body, .. }
        | Node::Baar { body, .. }
        | Node::Jabtak { body, .. } => {
            for s in body {
                collect_assigns(s, names);
            }
        }
        Node::Koshish { body, catch_body, .. } => {
            for s in body {
                collect_assigns(s, names);
            }
            for s in catch_body {
                collect_assigns(s, names);
            }
        }
        _ => {}
    }
}

/// Does this subtree contain a koshish? Gates the handler-stack bookkeeping.
fn uses_koshish(node: &Spanned<Node>) -> bool {
    match &node.node {
        Node::Koshish { .. } => true,
        Node::Banao { body, .. }
        | Node::HarRange { body, .. }
        | Node::HarList { body, .. }
        | Node::Baar { body, .. }
        | Node::Jabtak { body, .. } => body.iter().any(uses_koshish),
        Node::Agar { then_body, else_ifs, else_body, .. } => {
            then_body.iter().any(uses_koshish)
                || else_ifs.iter().any(|(_, b)| b.iter().any(uses_koshish))
                || else_body.as_ref().map_or(false, |b| b.iter().any(uses_koshish))
        }
        _ => false,
    }
}

// ----------------------------------------------------------------
// Helpers
// ----------------------------------------------------------------

fn prototype(name: &str, params: &[Param]) -> String {
    if params.is_empty() {
        format!("WowValue f_{name}(void);\n")
    } else {
        let ps: Vec<&str> = params.iter().map(|_| "WowValue").collect();
        format!("WowValue f_{name}({});\n", ps.join(", "))
    }
}

fn binop_fn(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "wow_add",
        BinOp::Sub => "wow_sub",
        BinOp::Mul => "wow_mul",
        BinOp::Div => "wow_div",
        BinOp::Mod => "wow_mod",
        BinOp::Eq => "wow_eq",
        BinOp::NotEq => "wow_neq",
        BinOp::Lt => "wow_lt",
        BinOp::Lte => "wow_lte",
        BinOp::Gt => "wow_gt",
        BinOp::Gte => "wow_gte",
        BinOp::And => "wow_and",
        BinOp::Or => "wow_or",
    }
}

/// tools whose argument is an implicit-`x` predicate.
fn is_higher_order(name: &str) -> bool {
    matches!(name, "badlo" | "chuno" | "dhundo" | "guroh")
}

/// tools and shared keywords implemented in the C runtime.
fn is_builtin(name: &str) -> bool {
    matches!(
        name,
        // math
        "round" | "round_up" | "round_down" | "square_root" | "power"
            | "absolute" | "random" | "random_number"
        // strings
            | "lambai" | "bara_likho" | "chota_likho" | "saaf" | "toro" | "milao" | "tabdeel"
        // collections
            | "ginti" | "jama" | "max" | "min" | "pehla" | "aakhri" | "ulta"
            | "shamil" | "alag" | "silsila" | "tukre" | "flatten" | "tarteeb"
            | "phento"
        // higher-order (also matched earlier)
            | "badlo" | "chuno" | "dhundo" | "guroh" | "joro"
        // shared
            | "intezar"
        // objects
            | "mafta" | "qeemtain" | "key_hai" | "hata"
    )
}

fn escape_c(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out
}
