use crate::ast::{BinOp, HttpMethod, InterpolPart, Node, Spanned};

/// Walk the AST and emit Node.js JavaScript.
///
/// JavaScript is dynamically typed like wow, so this backend is a fairly direct
/// translation — no runtime value type is needed. auzaar lives in
/// runtime/auzaar/auzaar.js (written next to the output by the CLI) and is
/// required at the top. Phase 1 covers the core language; the web keywords
/// (server / rasta / jawab / lao) arrive in a later phase.
pub fn generate(ast: &Spanned<Node>) -> String {
    let mut out = String::new();
    out.push_str("// Generated by wow — Code likho. Wow bolo.\n");
    out.push_str("'use strict';\n");
    out.push_str("const _auzaar = require('./auzaar.js');\n");
    out.push_str("const { fmt, bol, pucho, truthy, intezar, taqseem, baaqi,\n");
    out.push_str("        badlo, chuno, joro, dhundo, shamil, ginti, jama, max, min,\n");
    out.push_str("        tarteeb, ulta, alag, flatten, tukre, pehla, aakhri, phento,\n");
    out.push_str("        guroh, silsila, toro, milao, saaf, tabdeel, lambai,\n");
    out.push_str("        bara_likho, chota_likho, random, random_number,\n");
    out.push_str("        round, round_up, round_down, square_root, power, absolute } = _auzaar;\n\n");

    if let Node::Program(stmts) = &ast.node {
        // Wrap the program so an uncaught wow error prints a friendly Roman Urdu
        // line (like the C target) instead of a JavaScript stack trace. Function
        // declarations are block-hoisted, so source order still works inside.
        out.push_str("try {\n");

        // A program that uses server/rasta/jawab gets an Express app, wired up
        // automatically so a beginner never writes `app = express()` or
        // `(req, res)`. Express handles routes registered after listen(), so we
        // can emit everything in source order.
        if stmts.iter().any(uses_web) {
            out.push_str("    const _express = require('express');\n");
            out.push_str("    const _app = _express();\n\n");
        }
        for stmt in stmts {
            out.push_str(&gen_node(stmt, 1));
        }

        out.push_str("} catch (_e) {\n");
        out.push_str("    console.error('Ghalti: ' + ((_e && _e.message !== undefined) ? _e.message : _e));\n");
        out.push_str("    process.exit(1);\n");
        out.push_str("}\n");
    }

    out
}

/// Does this subtree use any of the web keywords (server / rasta / jawab)?
fn uses_web(node: &Spanned<Node>) -> bool {
    match &node.node {
        Node::Server(_) | Node::Rasta { .. } | Node::Jawab(_) => true,
        Node::ArduinoShuru(b) | Node::ArduinoChalao(b) | Node::Kaam { body: b, .. } => {
            b.iter().any(uses_web)
        }
        Node::Agar { then_body, else_ifs, else_body, .. } => {
            then_body.iter().any(uses_web)
                || else_ifs.iter().any(|(_, b)| b.iter().any(uses_web))
                || else_body.as_ref().map_or(false, |b| b.iter().any(uses_web))
        }
        Node::HarRange { body, .. }
        | Node::HarList { body, .. }
        | Node::Baar { body, .. }
        | Node::Jabtak { body, .. } => body.iter().any(uses_web),
        _ => false,
    }
}

fn gen_node(node: &Spanned<Node>, depth: usize) -> String {
    let pad = "    ".repeat(depth);
    match &node.node {
        Node::Kaam { naam, params, body } => {
            let ps: Vec<String> = params
                .iter()
                .map(|p| match &p.default {
                    Some(def) => format!("v_{} = {}", p.name, gen_expr(def)),
                    None => format!("v_{}", p.name),
                })
                .collect();
            let mut s = format!("{pad}function f_{naam}({}) {{\n", ps.join(", "));
            for stmt in body {
                s.push_str(&gen_node(stmt, depth + 1));
            }
            s.push_str(&format!("{pad}}}\n\n"));
            s
        }

        Node::Assign { name, value } => {
            // `var` is function-scoped and re-declarable, matching wow scoping.
            format!("{pad}var v_{name} = {};\n", gen_expr(value))
        }

        Node::Bol(e) => format!("{pad}bol({});\n", gen_expr(e)),
        Node::Do(e) => format!("{pad}return {};\n", gen_expr(e)),
        Node::Roko => format!("{pad}break;\n"),
        Node::Aage => format!("{pad}continue;\n"),

        Node::Agar { condition, then_body, else_ifs, else_body } => {
            let mut s = format!("{pad}if (truthy({})) {{\n", gen_expr(condition));
            s.push_str(&gen_block(then_body, depth + 1));
            for (cond, body) in else_ifs {
                s.push_str(&format!("{pad}}} else if (truthy({})) {{\n", gen_expr(cond)));
                s.push_str(&gen_block(body, depth + 1));
            }
            if let Some(body) = else_body {
                s.push_str(&format!("{pad}}} else {{\n"));
                s.push_str(&gen_block(body, depth + 1));
            }
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        Node::HarRange { var, from, to, body } => {
            // inclusive: 0 se 10 tak -> 0..10
            let mut s = format!(
                "{pad}for (let v_{var} = {}; v_{var} <= {}; v_{var}++) {{\n",
                gen_expr(from),
                gen_expr(to)
            );
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        Node::HarList { var, list, body } => {
            let mut s = format!("{pad}for (const v_{var} of {}) {{\n", gen_expr(list));
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        Node::Baar { times, body } => {
            let mut s = format!(
                "{pad}for (let _k = 0; _k < ({}); _k++) {{\n",
                gen_expr(times)
            );
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        Node::Jabtak { condition, body } => {
            let mut s = format!("{pad}while (truthy({})) {{\n", gen_expr(condition));
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        // ---- web (Node) ----

        // lao express  ->  const v_express = require("express")
        Node::Lao { name, path } => {
            format!("{pad}const v_{name} = require(\"{}\");\n", escape_js(path))
        }

        // rasta GET "/path" { ... }  ->  _app.get("/path", (req, res) => { ... })
        Node::Rasta { method, path, body } => {
            let m = match method {
                HttpMethod::Get => "get",
                HttpMethod::Post => "post",
                HttpMethod::Put => "put",
                HttpMethod::Delete => "delete",
            };
            let mut s = format!("{pad}_app.{m}(\"{}\", (req, res) => {{\n", escape_js(path));
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}});\n"));
            s
        }

        // server(port)  ->  _app.listen(port)
        Node::Server(port) => format!("{pad}_app.listen({});\n", gen_expr(port)),

        // jawab expr  ->  res.send(...). fmt() keeps a number from being read as
        // an HTTP status code, and formats values the wow way.
        Node::Jawab(e) => format!("{pad}res.send(fmt({}));\n", gen_expr(e)),

        // koshish { ... } pakdo ghalti { ... }  ->  try / catch
        Node::Koshish { body, catch_var, catch_body } => {
            let mut s = format!("{pad}try {{\n");
            s.push_str(&gen_block(body, depth + 1));
            s.push_str(&format!("{pad}}} catch (_e) {{\n"));
            if let Some(var) = catch_var {
                // bind the wow error name to a readable message string
                s.push_str(&format!(
                    "{pad}    var v_{var} = (_e && _e.message !== undefined) ? _e.message : fmt(_e);\n"
                ));
            }
            s.push_str(&gen_block(catch_body, depth + 1));
            s.push_str(&format!("{pad}}}\n"));
            s
        }

        // kaam shuru() on Node is just startup code that runs immediately.
        Node::ArduinoShuru(body) => gen_block(body, depth),
        Node::ArduinoChalao(_) => format!("{pad}/* chalao() Node par nahi chalta */\n"),

        // Anything else is an expression evaluated for its effect.
        _ => format!("{pad}{};\n", gen_expr(node)),
    }
}

fn gen_block(body: &[Spanned<Node>], depth: usize) -> String {
    let mut s = String::new();
    for stmt in body {
        s.push_str(&gen_node(stmt, depth));
    }
    s
}

fn gen_expr(node: &Spanned<Node>) -> String {
    match &node.node {
        Node::Number(n) => format!("{n}"),
        Node::Str(s) => format!("\"{}\"", escape_js(s)),
        Node::Bool(b) => if *b { "true".into() } else { "false".into() },
        Node::Null => "null".into(),
        Node::Identifier(id) => format!("v_{id}"),

        Node::Interpolated(parts) => {
            let mut s = String::from("`");
            for part in parts {
                match part {
                    InterpolPart::Text(t) => s.push_str(&escape_template(t)),
                    InterpolPart::Expr(e) => {
                        s.push_str("${fmt(");
                        s.push_str(&gen_expr(e));
                        s.push_str(")}");
                    }
                }
            }
            s.push('`');
            s
        }

        Node::List(items) => {
            let vals: Vec<String> = items.iter().map(gen_expr).collect();
            format!("[{}]", vals.join(", "))
        }

        Node::Negate(e) => format!("(-({}))", gen_expr(e)),
        Node::UnaryNot(e) => format!("(!truthy({}))", gen_expr(e)),

        Node::BinOp { op, left, right } => {
            let l = gen_expr(left);
            let r = gen_expr(right);
            match op {
                BinOp::And => format!("(truthy({l}) && truthy({r}))"),
                BinOp::Or => format!("(truthy({l}) || truthy({r}))"),
                // route through helpers that raise on divide-by-zero
                BinOp::Div => format!("taqseem({l}, {r})"),
                BinOp::Mod => format!("baaqi({l}, {r})"),
                _ => format!("({l} {} {r})", binop_sym(op)),
            }
        }

        Node::Ternary { condition, then_val, else_val } => {
            format!(
                "(truthy({}) ? ({}) : ({}))",
                gen_expr(condition),
                gen_expr(then_val),
                gen_expr(else_val)
            )
        }

        Node::Pucho(prompt) => format!("pucho({})", gen_expr(prompt)),

        Node::Call { name, args } => gen_call(name, args),

        Node::Phir { value, calls } => {
            // `a phir f(b)` == `f(a, b)`
            let mut acc: Spanned<Node> = (**value).clone();
            for step in calls {
                let mut new_args = Vec::with_capacity(step.args.len() + 1);
                new_args.push(acc);
                new_args.extend(step.args.iter().cloned());
                acc = Spanned::new(
                    Node::Call { name: step.name.clone(), args: new_args },
                    step.span.clone(),
                );
            }
            gen_expr(&acc)
        }

        _ => "null /* unsupported expression on node target */".into(),
    }
}

fn gen_call(name: &str, args: &[Spanned<Node>]) -> String {
    // joro (reduce): the kid's expression uses two implicit names, acc and x.
    if name == "joro" && args.len() == 3 {
        let list = gen_expr(&args[0]);
        let reducer = gen_expr(&args[1]);
        let start = gen_expr(&args[2]);
        return format!("joro({list}, (v_acc, v_x) => ({reducer}), {start})");
    }

    // Higher-order auzaar tools: the kid's `x`-expression becomes an arrow fn.
    if is_higher_order(name) && args.len() == 2 {
        let list = gen_expr(&args[0]);
        let pred = gen_expr(&args[1]);
        return format!("{name}({list}, (v_x) => ({pred}))");
    }

    let a: Vec<String> = args.iter().map(gen_expr).collect();
    if is_builtin(name) {
        format!("{name}({})", a.join(", "))
    } else {
        format!("f_{name}({})", a.join(", "))
    }
}

fn is_higher_order(name: &str) -> bool {
    matches!(name, "badlo" | "chuno" | "dhundo" | "guroh")
}

fn is_builtin(name: &str) -> bool {
    matches!(
        name,
        "round" | "round_up" | "round_down" | "square_root" | "power"
            | "absolute" | "random" | "random_number"
            | "lambai" | "bara_likho" | "chota_likho" | "saaf" | "toro" | "milao" | "tabdeel"
            | "ginti" | "jama" | "max" | "min" | "pehla" | "aakhri" | "ulta"
            | "shamil" | "alag" | "silsila" | "tukre" | "flatten" | "tarteeb"
            | "badlo" | "chuno" | "dhundo" | "joro" | "guroh" | "phento"
            | "intezar"
    )
}

fn binop_sym(op: &BinOp) -> &'static str {
    match op {
        BinOp::Add => "+",
        BinOp::Sub => "-",
        BinOp::Mul => "*",
        BinOp::Div => "/",
        BinOp::Mod => "%",
        BinOp::Eq => "===",
        BinOp::NotEq => "!==",
        BinOp::Lt => "<",
        BinOp::Lte => "<=",
        BinOp::Gt => ">",
        BinOp::Gte => ">=",
        BinOp::And => "&&",
        BinOp::Or => "||",
    }
}

fn escape_js(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\t' => out.push_str("\\t"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out
}

fn escape_template(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '`' => out.push_str("\\`"),
            '\\' => out.push_str("\\\\"),
            '$' => out.push_str("\\$"),
            _ => out.push(c),
        }
    }
    out
}
