use crate::ast::{Node, Spanned};

/// Walk the AST and emit valid Node.js JavaScript.
/// auzaar functions map to the JS runtime in runtime/auzaar/auzaar.js,
/// which is required at the top of every generated file.
/// npm packages imported with lao map directly to require() calls.
pub fn generate(ast: &Spanned<Node>) -> String {
    let mut out = String::new();

    out.push_str("// Generated by wow\n");
    out.push_str("const _auzaar = require('./auzaar.js');\n");
    out.push_str("const { badlo, chuno, joro, dhundo, shamil, ginti, jama, max, min,\n");
    out.push_str("        tarteeb, ulta, alag, flatten, tukre, pehla, aakhri, phento,\n");
    out.push_str("        guroh, silsila, toro, milao, saaf, tabdeel, lambai,\n");
    out.push_str("        bara_likho, chota_likho, random, random_number,\n");
    out.push_str("        round, round_up, round_down, square_root, power, absolute } = _auzaar;\n\n");

    if let Node::Program(stmts) = &ast.node {
        for stmt in stmts {
            out.push_str(&gen_node(stmt, 0));
        }
    }

    out
}

fn gen_node(node: &Spanned<Node>, depth: usize) -> String {
    let indent = "    ".repeat(depth);
    match &node.node {
        Node::Bol(expr) => {
            format!("{indent}console.log({});\n", gen_expr(expr))
        }
        Node::Server(port) => {
            format!("{indent}app.listen({}, () => console.log('Server chal raha hai'));\n",
                gen_expr(port))
        }
        // TODO: implement remaining nodes in Phase 5
        _ => format!("{indent}/* TODO */\n"),
    }
}

fn gen_expr(node: &Spanned<Node>) -> String {
    match &node.node {
        Node::Number(n)      => n.to_string(),
        Node::Str(s)         => format!("\"{s}\""),
        Node::Bool(b)        => if *b { "true".into() } else { "false".into() },
        Node::Null           => "null".into(),
        Node::Identifier(id) => id.clone(),
        _                    => "/* TODO */".into(),
    }
}
